---
title: "The map of COVID-19 in Portugal"
description: |
  A brief summary of the COVID-19 distribution in in Portugal.
author:
  - name: Xinying Xu
    url: https://example.com/norajones
date: 08-28-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, error = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
```


```{r}
# get the COVID-19 data in Portugal.
pt_comfirmed <- read_csv(here::here("data/confirmed_global.csv")) %>% 
  rename( Country = "Country/Region") %>% 
  filter(Country == "Portugal") %>%
  select(-`Province/State`) %>% 
  pivot_longer(cols = c(-Country:-Long),
               names_to = "Date",
               values_to = "Accumulated_Comfirmed")
```

```{r}
pt_recovered <- read_csv(here::here("data/recovered_global.csv")) %>% 
  rename( Country = "Country/Region") %>% 
  filter(Country == "Portugal") %>%
  select(-`Province/State`) %>% 
  pivot_longer(cols = c(-Country:-Long),
               names_to = "Date",
               values_to = "Accumulated_recovered")
```

```{r}
pt_dead <- read_csv(here::here("data/deaths_global.csv")) %>% 
  rename( Country = "Country/Region") %>% 
  filter(Country == "Portugal") %>%
  select(-`Province/State`) %>% 
  pivot_longer(cols = c(-Country:-Long),
               names_to = "Date",
               values_to = "Accumulated_dead")
```

```{r}
combined_pt <- pt_comfirmed %>% 
  full_join(pt_recovered, by = c("Country", "Lat","Long","Date")) %>% 
  full_join(pt_dead, by = c("Country", "Lat","Long","Date"))
```


```{r}
newly_pt <- read_csv(here::here("data/newly-cases.csv")) %>% 
  rename( country = "countriesAndTerritories") %>% 
  filter(country == "Portugal")
```

```{r}
vaccine_pt <- read_csv(here::here("data/vaccination_eu.csv")) %>% 
  filter(ReportingCountry == "PT")
```

